website/urls.py
# website/urls.py

from django.urls import path
from website import views
from website.views import custom_404_view

app_name = "website"


urlpatterns = [

    # ----------------------------------
    # region CLEAR CACHE
    
    path("clearcache/", views.clear_cache, name="clear_cache"),

    # endregion CLEAR CACHE
    # ----------------------------------
  

    # ----------------------------------
    # region CORE

    path("", views.index, name="index"),
    # path(f"{settings.GLOBAL_CATEGORY_PREFIX[1:]}", views.category, name="category"),
    path("about/", views.about, name="about"),
    # path("tags/", views.topics, name="topics"),
    path("archive/", views.archive, name="archive"),
    path("legal/", views.legal_index, name="legal_index"),
    path("legal/<slug>/", views.legal_single, name="legal_single"),
    
    # endregion CORE
    # ----------------------------------


    # ----------------------------------
    # region COMPANY
    
    path("directory/", views.company_index, name="company_index"),
    path("reviews/best/<slug:slug>/", views.company_collection, name="company_collection"),
    path("review/<slug>", views.company_single, name="company_single"),

    # endregion COMPANY
    # ----------------------------------


    # ----------------------------------
    # region TOOLS
    
    path("tools/", views.tools_index, name="tools_index"),
    path("tool/<slug>/", views.tools_single, name="tools_single"),

    # endregion TOOLS
    # ----------------------------------


]

handler404 = custom_404_view

website/models.py
# website/models.py

from django.db import models

class Company(models.Model):
    """
    Model representing a company.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    url = models.URLField(blank=True, null=True)
    serply_link = models.URLField(blank=True, null=True)
    logo = models.URLField(blank=True, null=True)
    one_liner = models.CharField(max_length=100,blank=True, null=True)
    short_description = models.CharField(max_length=255,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    article = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=255,blank=True, null=True)
    homepage_screenshot = models.URLField(blank=True, null=True)
    YEAR_CHOICES = [
        (str(year), str(year)) for year in range(1900, 2101)
        ]
    year_founded = models.IntegerField(blank=True, null=True, choices=YEAR_CHOICES)
    has_affiliate_program = models.BooleanField(default=False,blank=True, null=True)
    affiliate_signup_url = models.URLField(null=True, blank=True)
    affiliate_login_url = models.URLField(null=True, blank=True)
    COMPANY_TYPE_CHOICES = [
        (1, 'Software'),
        (2, 'Service Provider'),
        (3, 'Local Business'),
        (4, 'Merchant Account Provider'),
    ]
    company_type = models.IntegerField(
        choices=COMPANY_TYPE_CHOICES,
    )
    categories = models.ManyToManyField('CompanyCategory', blank=True)
    alternatives = models.ManyToManyField('self', symmetrical=True, blank=True,)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class CompanyCategory(models.Model):
    """
    Model representing a company category.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  
    name = models.CharField(max_length=255, unique=True)  
    slug = models.SlugField(unique=True)  
    description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Company Categories'

    def __str__(self):
        return self.name


class Feature(models.Model):
    """
    Model representing a feature.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    feature = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    company = models.ForeignKey(Company, related_name='features', on_delete=models.CASCADE)

    def __str__(self):
        return self.feature


class Pricing(models.Model):
    """
    Model representing the pricing information for a company.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    has_free_plan = models.BooleanField(null=True, blank=True, default=None)
    has_free_trial = models.BooleanField(null=True, blank=True, default=None)
    is_open_source = models.BooleanField(null=True, blank=True, default=None)
    PRICING_MODEL_CHOICES = [
        ('monthly', 'Monthly'),
        ('yearly', 'Yearly'),
        ('one time', 'One Time'),
    ]
    pricing_model = models.IntegerField(
        choices=PRICING_MODEL_CHOICES,
        blank=True,
        null=True,
    )
    company = models.ForeignKey(Company, related_name='pricing', related_query_name='pricing', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pricing'
        verbose_name_plural = 'Pricing'

    def __str__(self):
        return self.pricing_model
    
    company = models.ForeignKey(Company, related_name='pricing', related_query_name='pricing', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pricing'
        verbose_name_plural = 'Pricing'

    def __str__(self):
        return self.pricing_model

website/views.py
# website/views.py

import os
from django.core.cache import cache
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, reverse
from .models import Company, CompanyCategory

from utils import conditional_cache_page, paginate_queryset


# ------------------------------
# ------------------------------
# region URL VIEWS


# --------------------
# region CORE

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="index", condition=not os.getenv("DEBUG"))
def index(request):
    """
    View function for the index page.
    """
    
    template = "website/index.html"

    items = Company.objects.all()
    categories = CompanyCategory.objects.all()

    # Paginate the list of companies
    pagination_context = paginate_queryset(request, items)

    context = {
        'items': pagination_context['items'], 
        'categories': categories,
        'elided_page_range': pagination_context['elided_page_range']
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="about", condition=not os.getenv("DEBUG"))
def about(request):
    """
    View function for the about page.
    """
    
    template = "website/core/about.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "About", "url": None},
        ]

    context = {
        "breadcrumbs": breadcrumbs,
    }
    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="legal_index", condition=not os.getenv("DEBUG"))
def legal_index(request):
    """
    View function for the legal index page.
    """

    template = "website/legal/legal.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "Legal", "url": None},
        ]
    
    context = {
        "breadcrumbs": breadcrumbs,
        "website_url": os.getenv("DOMAIN"),
        "website_name": os.getenv("WEBSITE_URL"),
    }
    
    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="legal_single", condition=not os.getenv("DEBUG"))
def legal_single(request, slug):
    """
    View function for a single legal detail page.
    """

    template = f"website/legal/{slug.replace('-', '_')}.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "Legal", "url": reverse("website:legal_index")},
            {"name": " ".join(slug.split("-")).title(), "url": None},
        ]

    context = {
        "breadcrumbs": breadcrumbs,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="archive", condition=not os.getenv("DEBUG"))
def archive(request):
    """
    View function for the archive page.
    """
    template = "website/core/archive.html"

    breadcrumbs = [
        {"name": "Home", "url": reverse('website:index')},
        {"name": "Archive", "url": None},
    ]

    # Query all categories and companies based on type
    softwares = Company.objects.filter(company_type=1) 

    # Query software categories and exclude categories with empty slugs
    software_categories = CompanyCategory.objects.filter(company__in=softwares).distinct().exclude(slug='')

    context = {
        "breadcrumbs": breadcrumbs,
        "softwares": softwares,
        "software_categories": software_categories,
    }
    
    return render(request, template, context)


def custom_404_view(request, exception=None):
    template = "website/404.html"
    return render(request, template, status=404)


# endregion CORE
# --------------------


# --------------------
# region COMPANY


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_index", condition=not os.getenv("DEBUG"))
def company_index(request):
    """
    View function for the company index page.
    """

    # Define the template to use
    template = "website/company/index.html"

    # Fetch all companies
    company_queryset = Company.objects.all()
    category_queryset = CompanyCategory.objects.all()

    # Paginate the list of companies
    companies = paginate_queryset(request, company_queryset)
    categories = paginate_queryset(request, category_queryset) 

    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Directory", "url": None},
    ]  

    context = {
        'items': companies,
        'categories': categories,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_single", condition=not os.getenv("DEBUG"))
def company_single(request, slug):
    """
    View function for a single company detail page.
    """
    # Fetch the specific company by the slug
    company = get_object_or_404(Company, slug=slug)
    
    # Define a mapping from company type to template path
    template_paths = {
        1: "website/company/software/single.html",
        2: "website/company/service_provider/single.html",
        3: "website/company/local_business/single.html",
        4: "website/company/merchant_account_provider/single.html",
    }

     # Get the template path based on the company type
    template = template_paths.get(company.company_type)

    context = {
        'item': company,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_collection", condition=not os.getenv("DEBUG"))
def company_collection(request, slug):
    """
    View function for a single company detail page.
    """
    template = "website/company/software/collection.html"

    # Fetch the specific category based on the slug
    category = get_object_or_404(CompanyCategory, slug=slug)

    # Fetch all companies in the category
    companies = Company.objects.filter(categories__name=category.name)

    if not companies.exists():
        raise Http404("No companies found for this category.")


    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Directory", "url": reverse("website:company_index")},
        {"name": category.name, "url": None},
    ]  

    context = {
        'items': companies,
        'category': category,
        'breadcrumbs': breadcrumbs,
    }

    return render(request, template, context)


# endregion COMPANY
# --------------------


# --------------------
# region TOOLS

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="tools_index", condition=not os.getenv("DEBUG"))
def tools_index(request):

    # Define the template to use
    template = "website/tools/index.html"

    # Fetch all companies
    # tools_queryset = Tools.objects.all()
    # category_queryset = ToolsCategory.objects.all()

    # Paginate the list of companies
    # tools = paginate_queryset(request, tools_queryset)
    # categories = paginate_queryset(request, category_queryset) 

    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Tools", "url": None},
    ]  

    context = {
        # 'items': tools,
        # 'categories': categories,
    }

    return render(request, template, context)

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="tools_single", condition=not os.getenv("DEBUG"))
def tools_single(request, slug):

    # Fetch the specific tool by the slug
    # tool = get_object_or_404(Tool, slug=slug)

    # Get the template path based on the tool type
    template = f"website/tools/single/{slug.replace('-','_')}.html"

    breadcrumbs: [
        {"name": "Home", "url": "/"},
        {"name": "Tools", "url": reverse("website:tools_index")},
        # {"name": "Combine Tools", "url": reverse('website:tools_collection_combine')},
    ]

    context = {
        # 'item': tool,
    }

    return render(request, template, context)


# endregion TOOLS
# --------------------





# ------------------------------
# region HELPER VIEWS


def clear_cache(request):
    password = request.GET.get("password")

    if password != "clearcache":
        return HttpResponse("Unauthorized", status=401)

    cache.clear()
    return HttpResponse("Cache cleared successfully")


# endregion HELPER FUNCTIONS
# ------------------------------

website/templates/website/partials/archive_cards.html
<!-- website/partials/archive_cards.html -->

{% load static %}
<section id="_archiveCards">
  {% for category in categories %}
    <section class="container">
      <div class="row my-15">
        <a href="/categories/{{ category.slug }}/"><h2 class="display-3 my-3">{{ category.name|title }}</h2></a>
        {% for company in category.company_set.all %}
          <div class="col-xl-4 col-lg-6 col-md-6 col-12">
            <div class="card mb-4 card-hover">
              <div class="d-flex justify-content-between align-items-center p-4">
                <div class="d-flex">
                  <div class="ms-3">
                    <h3 class="mb-1 h4"><a href="/companies/{{ company.slug }}/">{{ company.name }}</a></h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>
  {% endfor %}
</section>

website/templates/website/partials/archive_singles.html
<!-- archive_singles.html -->

{% load static %}
{% for item in items %}
  <div class="container col-6 my-10">
    <a href="{% url 'website:single' slug=item.slug %}">
      <h2 class="mt-10">{{ software.name|upper }}</h2>
    </a>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <a href="{% url 'website:single' slug=item.slug %}">
          {{ item.name }}
        </a>
      </li>
    </ul>
  </div>
{% endfor %}

website/templates/website/partials/breadcrumbs.html
<section id="_breadcrumbs">
  {% if homepage %}
  <div style="display: none;">
{% else %}
  <div class="border-bottom">
{% endif %}
      <div class="container my-2">
        <div class="row">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              {% for breadcrumb in breadcrumbs %}
                <li class="breadcrumb-item {% if not breadcrumb.url %}active{% endif %}" {% if not breadcrumb.url %}aria-current="page"{% endif %}>
                  {% if breadcrumb.url %}
                    <a href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a>
                  {% else %}
                    {{ breadcrumb.name }}
                  {% endif %}
                </li>
              {% endfor %}
            </ol>
          </nav>
        </div>
      </div>
    </div>
</section>

website/templates/website/partials/footer.html
{% load static %}

{% load static %}

<footer class="pt-lg-5 pt-5 footer bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-12">
                <div class="mt-4">
                    <a href="/"><img src="{% static 'website/images/brand/logo/logo-wordmark-serp_everything.svg' %}" alt="{{ website_name }} Logo" class="logo-inverse" /></a>
                    <div class="mt-8">
                        <div class="fs-3">
                            <a href="https://serp.ly/@serpapp/facebook" target="_blank"><img src="{% static 'website/images/svg/facebook.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/instagram" target="_blank"><img src="{% static 'website/images/svg/instagram.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/twitter" target="_blank"><img src="{% static 'website/images/svg/twitter.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/linkedin" target="_blank"><img src="{% static 'website/images/svg/linkedin.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/pinterest" target="_blank"><img src="{% static 'website/images/svg/pinterest.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/github" target="_blank"><img src="{% static 'website/images/svg/github.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/discord" target="_blank"><img src="{% static 'website/images/svg/discord.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/reddit" target="_blank"><img src="{% static 'website/images/svg/reddit.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                            <a href="https://serp.ly/@serpapp/youtube" target="_blank"><img src="{% static 'website/images/svg/youtube.svg' %}" height="15" width="15" class="logo-inverse mx-1"></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-6">
                <div class="mb-4">
                    {% comment %} <h3 class="fw-bold mb-3">Browse</h3> {% endcomment %}
                    <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
                        {% comment %} <li><a href="{% url 'website:about' %}" class="nav-link">About</a></li> {% endcomment %}
                        {% comment %} <li><a href="/blog/" class="nav-link">Blog</a></li> {% endcomment %}
                        {% comment %} <li><a href="/subscribe/" class="nav-link">Subscribe</a></li> {% endcomment %}
                        <li><a href="{% url 'website:archive' %}" class="nav-link">Archive</a></li>
                        {% comment %} <li><a href="#" class="nav-link">Links</a></li> {% endcomment %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-12">
                <div class="mb-4">
                    {% comment %} <h3 class="fw-bold mb-3">Contribute</h3> {% endcomment %}
                    <ul class="list-unstyled nav nav-footer flex-column nav-x-0">
                        {% comment %} <li><a href="https://serp.ly/@serp/advertise" class="nav-link">Advertise</a></li> {% endcomment %}
                        {% comment %} <li><a href="/contribute/" class="nav-link">Contribute</a></li> {% endcomment %}
                        {% comment %} <li><a href="https://serp.ly/@serp/submit-correction" class="nav-link">Submit Correction</a></li> {% endcomment %}
                    </ul>

                </div>
            </div>
            <div class="col-lg-3 col-md-12 col-12">
                <div class="mb-4">
                    {% comment %} <h3 class="fw-bold mb-3">Contact</h3> {% endcomment %}
                    {% comment %} <p>1644 S. Main Street <br> Beverly Hills CA, 90210</p> {% endcomment %}
                    {% comment %} <p>Phone: <span class="text-dark fw-semibold">(800) 867-5309</span></p> {% endcomment %}
                </div>
            </div>
        </div>
        <div class="container border-top mt-2">
            <div class="row align-items-center g-0 py-2">
                {% include 'website/partials/footer_dropup.html' %}
                <div class="col-12 col-md-6">
                    <nav class="nav nav-footer justify-content-center justify-content-md-end">
                        <a class="nav-link active ps-0" href="/legal/privacy-policy/">Privacy</a>
                        <a class="nav-link" href="/legal/terms-conditions/">Terms</a>
                        <a class="nav-link" href="/legal/affiliate-disclosure/">Affiliate Disclosure</a>
                        <a class="nav-link" href="/legal/dmca/">DMCA</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>

website/templates/website/partials/footer_dropup.html
<div class="col-md-6 col-12 text-center text-md-start">
  <div class="btn-group dropup">
    <button type="button" class="btn btn-sm" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">© SERP</button>
    <div class="dropdown-menu">
      <span class="dropdown-item text-muted">SERP BRANDS</span>
      <a class="dropdown-item" href="https://serp.everything" target="_blank">SERP</a>
      <a class="dropdown-item" href="https://serp.ai" target="_blank">SERP AI</a>
      <a class="dropdown-item" href="https://serp.fm" target="_blank">SERP FM</a>
      <a class="dropdown-item" href="https://serp.app" target="_blank/">SERP App</a>
      <a class="dropdown-item" href="https://serp.games" target="_blank/">SERP Games</a>
      <a class="dropdown-item" href="https://serp.wiki" target="_blank/">SERP Wiki</a>
      <a class="dropdown-item" href="https://serp.dev" target="_blank">SERP Dev</a>
      <a class="dropdown-item" href="https://serp.style" target="_blank/">SERP Style</a>
      <a class="dropdown-item" href="https://serp.site" target="_blank">SERP Site</a>
      <a class="dropdown-item" href="https://serp.media" target="_blank">SERP Media</a>
      <a class="dropdown-item" href="https://serpuniversity.com" target="_blank">SERP University</a>
      <div class="dropdown-divider"></div>
      <span class="dropdown-item text-muted">PARTNER BRANDS</span>
      <a class="dropdown-item" href="https://daft.fm" target="_blank">DAFT FM</a>
      <a class="dropdown-item" href="https://boxingundefeated.com" target="_blank">Boxing Undefeated</a>
      <a class="dropdown-item" href="https://devinschumacher.com" target="_blank">Devin Schumacher</a>
      <a class="dropdown-item" href="https://universityofguns.com" target="_blank">University of Guns</a>
      <a class="dropdown-item" href="https://www.petsmarketplc.com" target="_blank">Pets Marketplace</a>
      <a class="dropdown-item" href="https://merchantalternatives.com" target="_blank">Merchant Alternatives</a>
    </div>
  </div>
</div>

website/templates/website/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid px-0">
    <a class="navbar-brand" href="/">
      <img src="{% static 'website/images/brand/logo/logo-icon-serp_co.svg' %}" {{ website_name }} class="logo-inverse" height="40" /></a>
    <!-- Mobile view nav wrap -->

    <div class="ms-auto d-flex align-items-center order-lg-3">

      <ul class="navbar-nav navbar-right-wrap mx-2 flex-row"> <!-- 3 icons -->
        <div class="mx-2">
          <a href="#" class="form-check form-switch theme-switch btn btn-light btn-icon rounded-circle">
            <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" />
            <label class="form-check-label" for="flexSwitchCheckDefault"></label>
          </a>
        </div>
        {% include 'website/partials/navbar_profile.html' %}

      </ul>
    </div>

    <div>
      <!-- Button -->
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
        <span class="icon-bar top-bar mt-0"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
    </div>

    <!-- Collapse -->
    <div class="collapse navbar-collapse justify-content-between px-4" id="navbar-default">
      <ul class="navbar-nav">

        {% include 'website/partials/navbar_dropdown.html' %}


      </ul>
      {% comment %} <form class="mt-3 mt-lg-0 ms-lg-3 mb-0 d-flex align-items-center">
        <span class="position-absolute ps-3 search-icon"><i class="fe fe-search"></i></span>
        <input type="search" class="form-control ps-6" placeholder="Search" />
      </form> {% endcomment %}
    </div>
  </div>
</nav>

website/templates/website/partials/navbar_dropdown.html
{% load static %}

{% comment %} 
<li class="nav-item dropdown">
    <span class="nav-link dropdown-toggle" id="navbarSingle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bs-display="static">Blog</span>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{% url 'website:blog_index' %}">Blog</a></li>
        <hr class="dropdown-divider">
        <li><a class="dropdown-item" href="#">Blog</a></li>
    </ul>
</li> {% endcomment %}


<li class="nav-item dropdown">
    <span class="nav-link dropdown-toggle" id="navbarSingle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bs-display="static">AI Tools</span>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/directory/">Directory</a></li>
        <li><a class="dropdown-item" href="{% url 'website:company_collection' 'artificial-intelligence-tools' %}">Artificial Intelligence Tools</a></li>
        <hr class="dropdown-divider">
    </ul>
</li>


<li class="nav-item dropdown">
    <span class="nav-link dropdown-toggle" id="navbarSingle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-bs-display="static">Tools</span>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/tools/">Tools</a></li>
        <hr class="dropdown-divider">
        <li><a class="dropdown-item" href="/tool/combine-csv-files/">Combine CSVs</a></li>
        <li><a class="dropdown-item" href="/tool/json-to-csv-converter/">JSON to CSV</a></li>
        <li><a class="dropdown-item" href="/tool/csv-to-json-converter/">CSV to JSON</a></li>
        <li><a class="dropdown-item" href="/tool/count-characters/">Character Counter</a></li>
        <li><a class="dropdown-item" href="/tool/word-counter/">Word Counter</a></li>
        <li><a class="dropdown-item" href="/tool/sentence-counter/">Sentence Counter</a></li>
        <li><a class="dropdown-item" href="/tool/paragraph-counter/">Paragraph Counter</a></li>
        <li><a class="dropdown-item" href="/tool/token-counter/">Token Counter</a></li>
    </ul>
</li>

website/templates/website/partials/pagination.html
<!-- pagination.html -->

<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&laquo;</a>
        </li>
        {% endif %}

        {% for page_number in elided_page_range %}
            {% if page_number == page_obj.paginator.ELLIPSIS %}
            <li class="page-item disabled">
                <a class="page-link">...</a>
            </li>
            {% else %}
            <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">&raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">&raquo;&raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>