website/urls.py
# website/urls.py

from django.urls import path
from website import views
from website.views import custom_404_view

app_name = "website"


urlpatterns = [

    # ----------------------------------
    # region CLEAR CACHE
    
    path("clearcache/", views.clear_cache, name="clear_cache"),

    # endregion CLEAR CACHE
    # ----------------------------------
  

    # ----------------------------------
    # region CORE

    path("", views.index, name="index"),
    # path(f"{settings.GLOBAL_CATEGORY_PREFIX[1:]}", views.category, name="category"),
    path("about/", views.about, name="about"),
    # path("tags/", views.topics, name="topics"),
    path("archive/", views.archive, name="archive"),
    path("legal/", views.legal_index, name="legal_index"),
    path("legal/<slug>/", views.legal_single, name="legal_single"),
    
    # endregion CORE
    # ----------------------------------


    # ----------------------------------
    # region COMPANY
    
    path("directory/", views.company_index, name="company_index"),
    path("reviews/best/<slug:slug>/", views.company_collection, name="company_collection"),
    path("review/<slug>", views.company_single, name="company_single"),

    # endregion COMPANY
    # ----------------------------------


    # ----------------------------------
    # region TOOLS
    
    path("tools/", views.tools_index, name="tools_index"),
    path("tool/<slug>/", views.tools_single, name="tools_single"),

    # endregion TOOLS
    # ----------------------------------


]

handler404 = custom_404_view

website/models.py
# website/models.py

from django.db import models

class Company(models.Model):
    """
    Model representing a company.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    url = models.URLField(blank=True, null=True)
    serply_link = models.URLField(blank=True, null=True)
    logo = models.URLField(blank=True, null=True)
    one_liner = models.CharField(max_length=100,blank=True, null=True)
    short_description = models.CharField(max_length=255,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    article = models.TextField(blank=True, null=True)
    address = models.CharField(max_length=255,blank=True, null=True)
    homepage_screenshot = models.URLField(blank=True, null=True)
    YEAR_CHOICES = [
        (str(year), str(year)) for year in range(1900, 2101)
        ]
    year_founded = models.IntegerField(blank=True, null=True, choices=YEAR_CHOICES)
    has_affiliate_program = models.BooleanField(default=False,blank=True, null=True)
    affiliate_signup_url = models.URLField(null=True, blank=True)
    affiliate_login_url = models.URLField(null=True, blank=True)
    COMPANY_TYPE_CHOICES = [
        (1, 'Software'),
        (2, 'Service Provider'),
        (3, 'Local Business'),
        (4, 'Merchant Account Provider'),
    ]
    company_type = models.IntegerField(
        choices=COMPANY_TYPE_CHOICES,
    )
    categories = models.ManyToManyField('CompanyCategory', blank=True)
    alternatives = models.ManyToManyField('self', symmetrical=True, blank=True,)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class CompanyCategory(models.Model):
    """
    Model representing a company category.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  
    name = models.CharField(max_length=255, unique=True)  
    slug = models.SlugField(unique=True)  
    description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Company Categories'

    def __str__(self):
        return self.name


class Feature(models.Model):
    """
    Model representing a feature.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    feature = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    company = models.ForeignKey(Company, related_name='features', on_delete=models.CASCADE)

    def __str__(self):
        return self.feature


class Pricing(models.Model):
    """
    Model representing the pricing information for a company.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    has_free_plan = models.BooleanField(null=True, blank=True, default=None)
    has_free_trial = models.BooleanField(null=True, blank=True, default=None)
    is_open_source = models.BooleanField(null=True, blank=True, default=None)
    PRICING_MODEL_CHOICES = [
        ('monthly', 'Monthly'),
        ('yearly', 'Yearly'),
        ('one time', 'One Time'),
    ]
    pricing_model = models.IntegerField(
        choices=PRICING_MODEL_CHOICES,
        blank=True,
        null=True,
    )
    company = models.ForeignKey(Company, related_name='pricing', related_query_name='pricing', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pricing'
        verbose_name_plural = 'Pricing'

    def __str__(self):
        return self.pricing_model
    
    company = models.ForeignKey(Company, related_name='pricing', related_query_name='pricing', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pricing'
        verbose_name_plural = 'Pricing'

    def __str__(self):
        return self.pricing_model

website/views.py
# website/views.py

import os
from django.core.cache import cache
from django.http import Http404, HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, reverse
from .models import Company, CompanyCategory

from utils import conditional_cache_page, paginate_queryset


# ------------------------------
# ------------------------------
# region URL VIEWS


# --------------------
# region CORE

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="index", condition=not os.getenv("DEBUG"))
def index(request):
    """
    View function for the index page.
    """
    
    template = "website/index.html"

    items = Company.objects.all()
    categories = CompanyCategory.objects.all()

    # Paginate the list of companies
    pagination_context = paginate_queryset(request, items)

    context = {
        'items': pagination_context['items'], 
        'categories': categories,
        'elided_page_range': pagination_context['elided_page_range']
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="about", condition=not os.getenv("DEBUG"))
def about(request):
    """
    View function for the about page.
    """
    
    template = "website/core/about.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "About", "url": None},
        ]

    context = {
        "breadcrumbs": breadcrumbs,
    }
    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="legal_index", condition=not os.getenv("DEBUG"))
def legal_index(request):
    """
    View function for the legal index page.
    """

    template = "website/legal/legal.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "Legal", "url": None},
        ]
    
    context = {
        "breadcrumbs": breadcrumbs,
        "website_url": os.getenv("DOMAIN"),
        "website_name": os.getenv("WEBSITE_URL"),
    }
    
    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="legal_single", condition=not os.getenv("DEBUG"))
def legal_single(request, slug):
    """
    View function for a single legal detail page.
    """

    template = f"website/legal/{slug.replace('-', '_')}.html"

    breadcrumbs = [
            {"name": "Home", "url": reverse("website:index")},
            {"name": "Legal", "url": reverse("website:legal_index")},
            {"name": " ".join(slug.split("-")).title(), "url": None},
        ]

    context = {
        "breadcrumbs": breadcrumbs,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="archive", condition=not os.getenv("DEBUG"))
def archive(request):
    """
    View function for the archive page.
    """
    template = "website/core/archive.html"

    breadcrumbs = [
        {"name": "Home", "url": reverse('website:index')},
        {"name": "Archive", "url": None},
    ]

    # Query all categories and companies based on type
    softwares = Company.objects.filter(company_type=1) 

    # Query software categories and exclude categories with empty slugs
    software_categories = CompanyCategory.objects.filter(company__in=softwares).distinct().exclude(slug='')

    context = {
        "breadcrumbs": breadcrumbs,
        "softwares": softwares,
        "software_categories": software_categories,
    }
    
    return render(request, template, context)


def custom_404_view(request, exception=None):
    template = "website/404.html"
    return render(request, template, status=404)


# endregion CORE
# --------------------


# --------------------
# region COMPANY


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_index", condition=not os.getenv("DEBUG"))
def company_index(request):
    """
    View function for the company index page.
    """

    # Define the template to use
    template = "website/company/index.html"

    # Fetch all companies
    company_queryset = Company.objects.all()
    category_queryset = CompanyCategory.objects.all()

    # Paginate the list of companies
    companies = paginate_queryset(request, company_queryset)
    categories = paginate_queryset(request, category_queryset) 

    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Directory", "url": None},
    ]  

    context = {
        'items': companies,
        'categories': categories,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_single", condition=not os.getenv("DEBUG"))
def company_single(request, slug):
    """
    View function for a single company detail page.
    """
    # Fetch the specific company by the slug
    company = get_object_or_404(Company, slug=slug)
    
    # Define a mapping from company type to template path
    template_paths = {
        1: "website/company/software/single.html",
        2: "website/company/service_provider/single.html",
        3: "website/company/local_business/single.html",
        4: "website/company/merchant_account_provider/single.html",
    }

     # Get the template path based on the company type
    template = template_paths.get(company.company_type)

    context = {
        'item': company,
    }

    return render(request, template, context)


@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="company_collection", condition=not os.getenv("DEBUG"))
def company_collection(request, slug):
    """
    View function for a single company detail page.
    """
    template = "website/company/software/collection.html"

    # Fetch the specific category based on the slug
    category = get_object_or_404(CompanyCategory, slug=slug)

    # Fetch all companies in the category
    companies = Company.objects.filter(categories__name=category.name)

    if not companies.exists():
        raise Http404("No companies found for this category.")


    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Directory", "url": reverse("website:company_index")},
        {"name": category.name, "url": None},
    ]  

    context = {
        'items': companies,
        'category': category,
        'breadcrumbs': breadcrumbs,
    }

    return render(request, template, context)


# endregion COMPANY
# --------------------


# --------------------
# region TOOLS

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="tools_index", condition=not os.getenv("DEBUG"))
def tools_index(request):

    # Define the template to use
    template = "website/tools/index.html"

    # Fetch all companies
    # tools_queryset = Tools.objects.all()
    # category_queryset = ToolsCategory.objects.all()

    # Paginate the list of companies
    # tools = paginate_queryset(request, tools_queryset)
    # categories = paginate_queryset(request, category_queryset) 

    breadcrumbs = [
        {"name": "Home", "url": reverse("website:index")},
        {"name": "Tools", "url": None},
    ]  

    context = {
        # 'items': tools,
        # 'categories': categories,
    }

    return render(request, template, context)

@conditional_cache_page(60 * 60 * 24 * 365, key_prefix="tools_single", condition=not os.getenv("DEBUG"))
def tools_single(request, slug):

    # Fetch the specific tool by the slug
    # tool = get_object_or_404(Tool, slug=slug)

    # Get the template path based on the tool type
    template = f"website/tools/single/{slug.replace('-','_')}.html"

    breadcrumbs: [
        {"name": "Home", "url": "/"},
        {"name": "Tools", "url": reverse("website:tools_index")},
        # {"name": "Combine Tools", "url": reverse('website:tools_collection_combine')},
    ]

    context = {
        # 'item': tool,
    }

    return render(request, template, context)


# endregion TOOLS
# --------------------





# ------------------------------
# region HELPER VIEWS


def clear_cache(request):
    password = request.GET.get("password")

    if password != "clearcache":
        return HttpResponse("Unauthorized", status=401)

    cache.clear()
    return HttpResponse("Cache cleared successfully")


# endregion HELPER FUNCTIONS
# ------------------------------

website/templates/website/company/software/partials/archive_cards.html
<!-- website/company/software/partials/archive_cards.html -->
{% load static %}
<section id="_archiveCards">
  <section class="container my-10">
    <div class="row">
      <!-- Listing categories -->
      {% for category in software_categories %}
        {% if category.slug %}
          <div class="col-xl-4 col-lg-6 col-md-6 col-12">
            <!-- Card -->
            <div class="card mb-4 card-hover">
              <div class="d-flex justify-content-between align-items-center p-4">
                <div class="d-flex">
                  <div class="ms-3">
                    <h3 class="mb-1">
                      <a href="{% url 'website:company_collection' slug=category.slug %}" class="text-inherit">
                        {{ category.name }}
                      </a>
                    </h3>
                    <p class="mb-0 fs-6">
                      <span class="me-2">
                        <span class="text-dark fw-medium">{{ category.company_set.count }}</span> Companies
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </section>
</section>

website/templates/website/company/software/partials/archive_singles.html
<!-- website/company/software/partials/archive_singles.html -->

{% load static %}
<div class="container col-md-8 col-lg-6"> 
  <div class="table-responsive"> 
    <table class="table">
      <thead>
        <tr>
          <th scope="col">
            <h2 class="mt-10"><a href="{% url 'website:company_index' %}">Directory</a></h2>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for software in softwares %}
        <tr>
          <td>
            <a href="{% url 'website:company_single' slug=software.slug %}">
              {{ software.name }}
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div> 
</div> 

website/templates/website/company/software/partials/card_row.html
<!-- website/company/software/partials/card_row.html -->

<div class="card card-bordered mb-3 card-hover cursor-pointer">
  <div class="card-body">
    <div class="d-xl-flex">
      <div class="col-3 d-flex flex-column justify-content-between">
        <img src="{{ item.homepage_screenshot }}" alt="{{ item.name }} featured thumbnail image" class="img-fluid" />
        <div>
          <a href="{% url 'website:company_single' item.slug %}" class="btn btn-outline-info w-100 mt-2 fs-6 ">{{ item.name }} Review</a>
        </div>
      </div>
      <div class="ms-xl-3 w-100 mt-3 mt-xl-0 d-flex flex-column justify-content-between">
        <div>
          <div class="d-flex justify-content-between align-items-center mb-2">
            <h2 class="mb-1"><a href="{{ item.serply_link }}" rel="noopener noreferrer nofollow sponsored" target="_blank" class="text-inherit">{{ item.name }}</a></h2>
            <div id="_icon">
              <i class="bi bi-heart text-muted bookmark ms-3"></i>
              <i class="bi bi-bookmark text-muted bookmark ms-3"></i>
              <i class="bi bi-share text-muted bookmark ms-3"></i>

            </div>
          </div>
          <p class="mt-2">
            {% if item.one_liner %}
              {{ item.one_liner|safe }}
            {% else %}
              {{ item.short_description|truncatewords:20|safe }}
            {% endif %}
          </p>
        </div>
        <div class="mb-2">
          {% for category in item.categories.all|slice:':5' %}
              <a href="{% url 'website:company_collection' category.slug %}" class="btn btn-light btn-xs my-1">{{ category.name }}
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

website/templates/website/company/software/partials/category_badge.html
<h3 class="mb-1 fs-4"><span class="badge bg-info-soft ms-2"><a href="/tools/{{ category.slug }}" class="text-inherit">{{ category.name }}</a></span></h3>

website/templates/website/company/software/partials/sidebar.html
<div id="_sidebarTools" class="card border mb-6 mb-md-0 shadow-none">
  <div class="card-body py-3">
    <a class="fs-5 text-dark fw-semibold" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Categories
      <span class="float-end">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
        </svg>
      </span>
    </a>
    <div class="collapse" id="collapseExample">
      <div class="mt-3">
        {% for category in categories %}
          {% include 'website/company/software/partials/category_badge.html' %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>